DROP TABLE IF EXISTS qubit;
DROP TABLE IF EXISTS mapper;
DROP TABLE IF EXISTS reducer;
DROP TABLE IF EXISTS spout;
DROP TABLE IF EXISTS qubit;
DROP TABLE IF EXISTS qutrit;
DROP TABLE IF EXISTS states;
DROP TABLE IF EXISTS closure;
